/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/gyms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 암장 목록 (무한스크롤) */
        get: operations["getGyms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gyms/{gymId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 암장 상세 */
        get: operations["getGym"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gyms/{gymId}/check-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 암장 체크인 */
        post: operations["checkInGym"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gyms/{gymId}/check-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 암장 체크아웃 */
        post: operations["checkOutGym"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gyms/{gymId}/congestion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 시간대별 혼잡도 */
        get: operations["getGymCongestion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gyms/{gymId}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 리뷰 목록 (무한스크롤) */
        get: operations["getGymReviews"];
        put?: never;
        /** 리뷰 작성 */
        post: operations["createReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 기록 목록 (무한스크롤) */
        get: operations["getRecords"];
        put?: never;
        /** 기록 생성 */
        post: operations["createRecord"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records/{recordId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 기록 상세 */
        get: operations["getRecord"];
        put?: never;
        post?: never;
        /** 기록 삭제 */
        delete: operations["deleteRecord"];
        options?: never;
        head?: never;
        /** 기록 수정 */
        patch: operations["updateRecord"];
        trace?: never;
    };
    "/api/v1/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 게시글 목록 (무한스크롤) */
        get: operations["getPosts"];
        put?: never;
        /** 게시글 작성 */
        post: operations["createPost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/{postId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 게시글 상세 */
        get: operations["getPost"];
        put?: never;
        post?: never;
        /** 게시글 삭제 */
        delete: operations["deletePost"];
        options?: never;
        head?: never;
        /** 게시글 수정 */
        patch: operations["updatePost"];
        trace?: never;
    };
    "/api/v1/posts/{postId}/view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 게시글 조회수 증가 (세션당 1회 호출 권장) */
        post: operations["recordPostView"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/{postId}/like": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 좋아요 토글 */
        post: operations["togglePostLike"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/{postId}/bookmark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 북마크 토글 */
        post: operations["togglePostBookmark"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/{postId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 댓글 목록 (무한스크롤) */
        get: operations["getPostComments"];
        put?: never;
        /** 댓글 작성 */
        post: operations["createComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 정보 */
        get: operations["getMe"];
        put?: never;
        post?: never;
        /** 회원 탈퇴 */
        delete: operations["deleteMe"];
        options?: never;
        head?: never;
        /** 내 정보 수정 */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/api/v1/users/me/nickname-availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 닉네임 사용 가능 여부 (본인 현재 닉네임 제외) */
        get: operations["getMyNicknameAvailability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/followers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 팔로워 목록 */
        get: operations["getMyFollowers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/following": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 팔로잉 목록 */
        get: operations["getMyFollowing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/bookmarked-posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 저장한 게시글 (무한스크롤) */
        get: operations["getMyBookmarkedPosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/liked-posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 좋아요한 게시글 (무한스크롤) */
        get: operations["getMyLikedPosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 유저 프로필 */
        get: operations["getUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{userId}/follow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 팔로우 토글 */
        post: operations["toggleFollow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{userId}/public-records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 유저 공개 기록 목록 (프로필 그리드) */
        get: operations["getUserPublicRecords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/completion-week": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 최근 7일 완등 추이 (홈 차트) */
        get: operations["getCompletionWeekStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 알림 목록 (무한스크롤) */
        get: operations["getNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 알림 읽음 처리 */
        patch: operations["markNotificationsRead"];
        trace?: never;
    };
    "/api/v1/upload/presigned": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** S3 Presigned URL 발급 */
        post: operations["getPresignedUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Region: "SEOUL" | "GYEONGGI" | "INCHEON" | "BUSAN" | "DAEGU" | "DAEJEON" | "GWANGJU" | "ULSAN" | "SEJONG" | "GANGWON" | "CHUNGBUK" | "CHUNGNAM" | "JEONBUK" | "JEONNAM" | "GYEONGBUK" | "GYEONGNAM" | "JEJU";
        /** @enum {string} */
        Difficulty: "VB" | "V0" | "V1" | "V2" | "V3" | "V4" | "V5" | "V6" | "V7" | "V8" | "V9" | "V10" | "V_PLUS";
        /** @enum {string} */
        GymPerceivedDifficulty: "EASY" | "NORMAL" | "HARD";
        /** @enum {string} */
        CommunityCategory: "FREE" | "TIPS" | "REVIEW" | "MEETUP" | "GEAR";
        /** @enum {string} */
        NotificationType: "COMMENT" | "LIKE" | "FOLLOW" | "SYSTEM" | "GYM_UPDATE";
        /** @enum {string} */
        FacilityType: "PARKING" | "SHOWER" | "LOCKER" | "RENTAL" | "CAFE" | "WIFI" | "REST_AREA" | "TRAINING";
        /** @enum {string} */
        AttemptResult: "SEND" | "ATTEMPT" | "FLASH" | "ONSIGHT";
        /** @enum {string} */
        GymReviewFeature: "COOL_AIR" | "WIDE_STRETCH" | "VARIOUS_LEVEL" | "KIND_STAFF" | "EASY_PARKING" | "SHOWER_ROOM" | "CLEAN_FACILITY" | "GOOD_VENT";
        /** @enum {string} */
        Role: "ADMIN" | "MANAGER" | "GUEST";
        AuthorSummary: {
            /** Format: uuid */
            id: string;
            nickname: string;
            profileImage: string | null;
        };
        GymImage: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            gymId: string;
            url: string;
            order: number;
            /** Format: date-time */
            createdAt: string;
        };
        GymFacility: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            gymId: string;
            type: components["schemas"]["FacilityType"];
        };
        GymOpenHoursTimeSlot: {
            /** @description HH:mm */
            open: string;
            /** @description HH:mm */
            close: string;
        };
        GymOpenHours: {
            weekday?: components["schemas"]["GymOpenHoursTimeSlot"];
            saturday?: components["schemas"]["GymOpenHoursTimeSlot"];
            sunday?: components["schemas"]["GymOpenHoursTimeSlot"];
            holiday?: components["schemas"]["GymOpenHoursTimeSlot"];
            /** @description 비정기 휴무·안내 문구 */
            notice?: string;
        };
        GymListItem: {
            /** Format: uuid */
            id: string;
            name: string;
            address: string;
            region: components["schemas"]["Region"];
            phone: string | null;
            openHours: null | components["schemas"]["GymOpenHours"];
            congestion: number;
            /** @description 현재 체크인 기준 이용 인원 */
            visitorCount: number;
            /** @description 수용 인원(표시 상한) */
            visitorCapacity: number;
            latitude: number | null;
            longitude: number | null;
            description: string | null;
            avgRating: number;
            reviewCount: number;
            /** @description 웹사이트 URL */
            website?: string | null;
            /** @description 목록/카드용 썸네일 */
            thumbnailUrl?: string | null;
            instagramId?: string | null;
            /** @description 가격 정보 (암장별 JSON 구조) */
            priceInfo?: {
                [key: string]: unknown;
            } | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            facilities: components["schemas"]["GymFacility"][];
            images: components["schemas"]["GymImage"][];
        };
        GymDetail: components["schemas"]["GymListItem"] & {
            myCheckIn?: {
                /** Format: date-time */
                endsAt: string;
            } | null;
        };
        CheckInResult: {
            /** Format: date-time */
            endsAt: string;
        };
        CheckOutResult: {
            ok: boolean;
        };
        CongestionLog: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            gymId: string;
            dayOfWeek: number;
            hour: number;
            congestion: number;
            /** Format: date-time */
            createdAt: string;
        };
        PaginatedGymListItem: {
            items: components["schemas"]["GymListItem"][];
            nextCursor: string | null;
        };
        ReviewImage: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            reviewId: string;
            url: string;
            order: number;
            /** Format: date-time */
            createdAt: string;
        };
        Review: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            /** Format: uuid */
            gymId: string;
            rating: number;
            content: string;
            perceivedDifficulty?: components["schemas"]["GymPerceivedDifficulty"];
            features?: components["schemas"]["GymReviewFeature"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ReviewListItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            /** Format: uuid */
            gymId: string;
            rating: number;
            content: string;
            perceivedDifficulty?: components["schemas"]["GymPerceivedDifficulty"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            user: components["schemas"]["AuthorSummary"];
            features: components["schemas"]["GymReviewFeature"][];
            images: components["schemas"]["ReviewImage"][];
        };
        PaginatedReviewListItem: {
            items: components["schemas"]["ReviewListItem"][];
            nextCursor: string | null;
        };
        CreateReviewBody: {
            rating: number;
            content: string;
            features?: components["schemas"]["GymReviewFeature"][];
            imageUrls?: string[];
        };
        Route: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            sessionId: string;
            difficulty: components["schemas"]["Difficulty"];
            result: components["schemas"]["AttemptResult"];
            attempts: number;
            perceivedDifficulty?: components["schemas"]["GymPerceivedDifficulty"];
            memo: string | null;
            order: number;
            /** Format: date-time */
            createdAt: string;
        };
        SessionImage: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            sessionId: string;
            url: string;
            order: number;
            /** Format: date-time */
            createdAt: string;
        };
        GymSummary: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        RecordListItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            /** Format: uuid */
            gymId: string;
            /** Format: date-time */
            date: string;
            /** Format: date-time */
            startTime: string | null;
            /** Format: date-time */
            endTime: string | null;
            memo: string | null;
            isPublic: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            gym: components["schemas"]["GymSummary"];
            routes: components["schemas"]["Route"][];
            images: components["schemas"]["SessionImage"][];
        };
        RecordDetail: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            /** Format: uuid */
            gymId: string;
            /** Format: date-time */
            date: string;
            /** Format: date-time */
            startTime: string | null;
            /** Format: date-time */
            endTime: string | null;
            memo: string | null;
            isPublic: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            gym: {
                /** Format: uuid */
                id: string;
                name: string;
                address: string;
            };
            routes: components["schemas"]["Route"][];
            images: components["schemas"]["SessionImage"][];
            user: components["schemas"]["AuthorSummary"];
        };
        PaginatedRecordListItem: {
            items: components["schemas"]["RecordListItem"][];
            nextCursor: string | null;
        };
        CreateRouteBody: {
            difficulty: components["schemas"]["Difficulty"];
            result: components["schemas"]["AttemptResult"];
            /** @default 1 */
            attempts: number;
            memo?: string;
        };
        CreateSessionBody: {
            /** Format: uuid */
            gymId: string;
            /** Format: date-time */
            date: string;
            /** Format: date-time */
            startTime?: string;
            /** Format: date-time */
            endTime?: string;
            memo?: string;
            /** @default true */
            isPublic: boolean;
            routes: components["schemas"]["CreateRouteBody"][];
            imageUrls?: string[];
        };
        UpdateSessionBody: {
            /** Format: date-time */
            date?: string;
            /** Format: date-time */
            startTime?: string;
            /** Format: date-time */
            endTime?: string;
            memo?: string | null;
            isPublic?: boolean;
            routes?: components["schemas"]["CreateRouteBody"][];
            imageUrls?: string[];
        };
        PostTag: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            postId: string;
            name: string;
        };
        PostImage: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            postId: string;
            url: string;
            order: number;
            /** Format: date-time */
            createdAt: string;
        };
        Post: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            authorId: string;
            category: components["schemas"]["CommunityCategory"];
            title: string;
            content: string;
            viewCount: number;
            likeCount: number;
            commentCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PostListItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            authorId: string;
            category: components["schemas"]["CommunityCategory"];
            title: string;
            content: string;
            viewCount: number;
            likeCount: number;
            commentCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            author: components["schemas"]["AuthorSummary"];
            tags: components["schemas"]["PostTag"][];
            images: components["schemas"]["PostImage"][];
            likes?: {
                /** Format: uuid */
                id: string;
            }[];
            bookmarks?: {
                /** Format: uuid */
                id: string;
            }[];
        };
        PostDetail: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            authorId: string;
            category: components["schemas"]["CommunityCategory"];
            title: string;
            content: string;
            viewCount: number;
            likeCount: number;
            commentCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            author: components["schemas"]["AuthorSummary"];
            tags: components["schemas"]["PostTag"][];
            images: components["schemas"]["PostImage"][];
            likes?: {
                /** Format: uuid */
                id: string;
            }[];
            bookmarks?: {
                /** Format: uuid */
                id: string;
            }[];
        };
        PaginatedFollowUser: {
            items: components["schemas"]["AuthorSummary"][];
            /** Format: uuid */
            nextCursor: string | null;
        };
        PaginatedPostListItem: {
            items: components["schemas"]["PostListItem"][];
            nextCursor: string | null;
        };
        CreatePostBody: {
            category: components["schemas"]["CommunityCategory"];
            title: string;
            content: string;
            tags?: string[];
            imageUrls?: string[];
        };
        UpdatePostBody: {
            title?: string;
            content?: string;
            category?: components["schemas"]["CommunityCategory"];
            tags?: string[];
            imageUrls?: string[];
        };
        CommentWithAuthor: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            postId: string;
            /** Format: uuid */
            authorId: string;
            /** Format: uuid */
            parentId: string | null;
            content: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            author: components["schemas"]["AuthorSummary"];
        };
        CommentListItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            postId: string;
            /** Format: uuid */
            authorId: string;
            /** Format: uuid */
            parentId: string | null;
            content: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            author: components["schemas"]["AuthorSummary"];
            replies: components["schemas"]["CommentWithAuthor"][];
        };
        PaginatedCommentListItem: {
            items: components["schemas"]["CommentListItem"][];
            nextCursor: string | null;
        };
        CreateCommentBody: {
            content: string;
            /** Format: uuid */
            parentId?: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            homeGymId?: string | null;
            /** Format: email */
            email: string;
            nickname: string;
            bio: string | null;
            profileImage: string | null;
            coverImage: string | null;
            instagramId: string | null;
            youtubeUrl: string | null;
            maxDifficulty: components["schemas"]["Difficulty"];
            role: components["schemas"]["Role"];
            /** @description 체크인 후 자동 체크아웃까지 분 (기본 240) */
            checkInAutoDurationMinutes: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UserCounts: {
            following: number;
            followers: number;
            sessions: number;
        };
        ActiveCheckIn: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            gymId: string;
            gymName: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            endsAt: string;
        };
        UserMe: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            homeGymId?: string | null;
            /** Format: email */
            email: string;
            nickname: string;
            bio: string | null;
            profileImage: string | null;
            coverImage: string | null;
            instagramId: string | null;
            youtubeUrl: string | null;
            maxDifficulty: components["schemas"]["Difficulty"];
            role: components["schemas"]["Role"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            _count: components["schemas"]["UserCounts"];
            /** @description 방문한 서로 다른 암장 수 */
            visitCount: number;
            /** @description 완등(SEND) 누적 */
            sendCount: number;
            /** @description 체크인 후 자동 체크아웃까지 분 (기본 240) */
            checkInAutoDurationMinutes: number;
            /** @description Supabase에 연결된 소셜 로그인 (카카오·구글) */
            linkedProviders: ("KAKAO" | "GOOGLE")[];
            activeCheckIn: components["schemas"]["ActiveCheckIn"] | null;
        };
        UserProfile: {
            /** Format: uuid */
            id: string;
            nickname: string;
            bio: string | null;
            profileImage: string | null;
            coverImage: string | null;
            instagramId: string | null;
            youtubeUrl: string | null;
            maxDifficulty: components["schemas"]["Difficulty"];
            /** Format: date-time */
            createdAt: string;
            _count: components["schemas"]["UserCounts"];
            visitCount: number;
            sendCount: number;
            /** @description 최근 20주×7일 활동 강도 (0~4) */
            activityHeatmap: number[];
            /** @description 각 히트맵 셀 날짜 (yyyy-MM-dd), activityHeatmap과 동일 순서 */
            activityHeatmapDays: string[];
            followers?: {
                /** Format: uuid */
                id: string;
            }[];
        };
        UpdateUserBody: {
            nickname?: string;
            bio?: string;
            /** Format: uri */
            profileImage?: string;
            /** Format: uri */
            coverImage?: string;
            instagramId?: string;
            /** Format: uri */
            youtubeUrl?: string;
            maxDifficulty?: components["schemas"]["Difficulty"];
            /** @description 체크인 후 자동 체크아웃까지 분 */
            checkInAutoDurationMinutes?: number;
        };
        Notification: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            type: components["schemas"]["NotificationType"];
            title: string;
            message: string;
            isRead: boolean;
            link?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        PaginatedNotification: {
            items: components["schemas"]["Notification"][];
            nextCursor: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getGyms: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                region?: components["schemas"]["Region"];
                search?: string;
                sort?: "name" | "rating" | "congestion" | "reviewCount";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        payload: components["schemas"]["PaginatedGymListItem"];
                    };
                };
            };
        };
    };
    getGym: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gymId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        payload: components["schemas"]["GymDetail"];
                    };
                };
            };
        };
    };
    checkInGym: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gymId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        toast: string;
                        payload: components["schemas"]["CheckInResult"];
                    };
                };
            };
        };
    };
    checkOutGym: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gymId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        toast: string;
                        payload: components["schemas"]["CheckOutResult"];
                    };
                };
            };
        };
    };
    getGymCongestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gymId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        payload: components["schemas"]["CongestionLog"][];
                    };
                };
            };
        };
    };
    getGymReviews: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                gymId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        payload: components["schemas"]["PaginatedReviewListItem"];
                    };
                };
            };
        };
    };
    createReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gymId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReviewBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        toast: string;
                        payload: components["schemas"]["Review"];
                    };
                };
            };
        };
    };
    getRecords: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                month?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        payload: components["schemas"]["PaginatedRecordListItem"];
                    };
                };
            };
        };
    };
    createRecord: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        toast: string;
                        payload: components["schemas"]["RecordDetail"];
                    };
                };
            };
        };
    };
    getRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recordId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        payload: components["schemas"]["RecordDetail"];
                    };
                };
            };
        };
    };
    deleteRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recordId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        toast: string;
                        payload: null;
                    };
                };
            };
        };
    };
    updateRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recordId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSessionBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        toast: string;
                        payload: components["schemas"]["RecordDetail"];
                    };
                };
            };
        };
    };
    getPosts: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                category?: components["schemas"]["CommunityCategory"];
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        payload: components["schemas"]["PaginatedPostListItem"];
                    };
                };
            };
        };
    };
    createPost: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePostBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        toast: string;
                        payload: components["schemas"]["Post"];
                    };
                };
            };
        };
    };
    getPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        payload: components["schemas"]["PostDetail"];
                    };
                };
            };
        };
    };
    deletePost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        toast: string;
                        payload: null;
                    };
                };
            };
        };
    };
    updatePost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePostBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        toast: string;
                        payload: components["schemas"]["Post"];
                    };
                };
            };
        };
    };
    recordPostView: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        payload: {
                            viewCount: number;
                        };
                    };
                };
            };
        };
    };
    togglePostLike: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        payload: {
                            liked: boolean;
                        };
                    };
                };
            };
        };
    };
    togglePostBookmark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        payload: {
                            bookmarked: boolean;
                        };
                    };
                };
            };
        };
    };
    getPostComments: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                postId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        payload: components["schemas"]["PaginatedCommentListItem"];
                    };
                };
            };
        };
    };
    createComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommentBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        toast: string;
                        payload: components["schemas"]["CommentWithAuthor"];
                    };
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        payload: components["schemas"]["UserMe"];
                    };
                };
            };
        };
    };
    deleteMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        toast: string;
                        payload: unknown;
                    };
                };
            };
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        toast: string;
                        payload: components["schemas"]["User"];
                    };
                };
            };
        };
    };
    getMyNicknameAvailability: {
        parameters: {
            query: {
                nickname: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        payload: {
                            available: boolean;
                        };
                    };
                };
            };
        };
    };
    getMyFollowers: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        payload: components["schemas"]["PaginatedFollowUser"];
                    };
                };
            };
        };
    };
    getMyFollowing: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        payload: components["schemas"]["PaginatedFollowUser"];
                    };
                };
            };
        };
    };
    getMyBookmarkedPosts: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        payload: components["schemas"]["PaginatedPostListItem"];
                    };
                };
            };
        };
    };
    getMyLikedPosts: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        payload: components["schemas"]["PaginatedPostListItem"];
                    };
                };
            };
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        payload: components["schemas"]["UserProfile"];
                    };
                };
            };
        };
    };
    toggleFollow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        payload: {
                            following: boolean;
                        };
                    };
                };
            };
        };
    };
    getUserPublicRecords: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                /** @description 방문일 필터 (yyyy-MM-dd) */
                day?: string;
            };
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        payload: components["schemas"]["PaginatedRecordListItem"];
                    };
                };
            };
        };
    };
    getCompletionWeekStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        payload: {
                            points: {
                                /** Format: date */
                                date: string;
                                count: number;
                            }[];
                        };
                    };
                };
            };
        };
    };
    getNotifications: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                type?: components["schemas"]["NotificationType"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        payload: components["schemas"]["PaginatedNotification"];
                    };
                };
            };
        };
    };
    markNotificationsRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        toast: string;
                        payload: null;
                    };
                };
            };
        };
    };
    getPresignedUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description 원본 파일명 (확장자 포함) */
                    filename: string;
                    /** @description image/* 또는 video/* */
                    contentType: string;
                    /**
                     * @description S3 경로 세그먼트 (images | videos)
                     * @enum {string}
                     */
                    type: "images" | "videos";
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        payload: {
                            presignedUrl: string;
                            publicUrl: string;
                            /** @description {development|production}/{images|videos}/{name}_{ts}.{ext} */
                            key: string;
                            bucket: string;
                            /** @enum {string} */
                            type: "images" | "videos";
                        };
                    };
                };
            };
        };
    };
}
